### PR TITLE
Add support for Hard swish operator

### PR DESCRIPTION
**Pull request by Rjasuja**
Adds support for Hard Swish operator for all supported types

Signed-off-by: Ritul Jasuja <ritul.jasuja@intel.com>

### CODE REVIEW

**Review by RavirajSitaram — APPROVED** [review]
LGTM

**Comment by vbenni** [comment]
LGTM

**Comment by RavirajSitaram** [comment]
@JeevakaPrabu  Can you merge this PR?

**Comment by Nagamani71** [comment]
@Rjasuja could you please refactor the PR, Float16 support is already added

**Comment by Rjasuja** [comment]
@Nagamani71 Rebased and refactored.

**Comment by Nagamani71** [comment]
LGTM

**Pull request merged**
